# Generated by Django 5.1.2 on 2024-10-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_subscription_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium_member',
            field=models.BooleanField(default=False),
        ),
    ]
