# Generated by Django 5.1.2 on 2024-10-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cast/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('year', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cast', models.ManyToManyField(related_name='movies', to='movie.cast')),
                ('director', models.ManyToManyField(related_name='directed_movies', to='movie.cast')),
                ('genre', models.ManyToManyField(to='movie.genre')),
                ('language', models.ManyToManyField(to='movie.language')),
                ('quality', models.ManyToManyField(to='movie.quality')),
            ],
        ),
    ]
