# Generated by Django 5.1.2 on 2024-10-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_title_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
