# Generated by Django 5.1.2 on 2024-10-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='movies',
        ),
        migrations.AddField(
            model_name='herosection',
            name='movie',
            field=models.CharField(blank=True, choices=[(1, 'Vikram')], max_length=100, null=True),
        ),
    ]
