# Generated by Django 5.1.2 on 2024-10-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_herosection_movies_herosection_movie'),
        ('movie', '0002_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_sections', to='movie.movie'),
        ),
    ]
